### PR TITLE
Contribution/fix acm finding

### PR DESCRIPTION
**Pull request by sureshrupnar**

### CODE REVIEW

**Comment by robmoffat** [comment]
Don’t merge this with a failing build please

**Comment by sureshrupnar** [comment]
> Don’t merge this with a failing build please

Yes Rob, actually we created Environment variables in Github. This is not present in contribution branch. Branch will automatically sync and build will get success. Waiting for Sync to get latest code in Contribution branch.

**Comment by robmoffat** [comment]
Hi Suresh,

The build should still pass in Github even on the branch.  The branch shouldn't be running tests that won't work.

If you rename the tests to 'IT' then they will only be run on the master branch.  This is probably what you need to do.

**Comment by vaibhav-db** [comment]
> What's happened to JsonIdentity1ConfigTest and JsonIdentity2ConfigTest

We already covered functionality test cases for Identity classes. As we don't want to keep private and certificate on json file. we have remove these test cases and json files.

**Comment by robmoffat** [comment]
you need to merge this to symphony-java-toolkit-master now

**Pull request closed without merging**
