### PR TITLE
AdaptiveCard Help page for MS Teams

### PR DESCRIPTION
**Pull request by pankaj-a-khandelwal-db**

### CODE REVIEW

**Review by vaibhav-db — APPROVED** [review]

**Review by robmoffat — COMMENTED** [review]
Nice work, Pankaj!

What would be really nice is adding a couple of images to the README so that people can see what the effect of this is.

Would that be ok?

**Comment by pankaj-a-khandelwal-db** [comment]
Good idea - I will capture Symphony and MS Teams Help pages and add it to readme file

**Comment by pankaj-a-khandelwal-db** [comment]
Updated readme file with custom page samples

**Review by robmoffat — APPROVED** [review]
bloody lovely!

**Pull request merged**
